# Generated by Django 3.1.4 on 2020-12-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
